apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mavenapp
  labels:
    app: maven
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
      - name: mavencontainer
        image: meghanajshetty/maventomcat:latest
        ports:
        - containerPort: 8080
  
      
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: maventomcat
#   labels:
#     app: maven
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: cafestatic
#   template:
#     metadata:
#       labels:
#         app: cafestatic
#     spec:
#       containers:
#       - name: cafestatic
#         image: sreedocker123/cafewebimage:final
#         ports:
#         - containerPort: 80
